import { invoke } from "@tauri-apps/api/core";
import type { GradedSheet } from "$lib/types/generated/GradedSheet";

/**
 * Event names emitted by `commands::scan`. Frontend listeners use these
 * constants instead of bare strings so renames stay in sync.
 */
export const TASK_PROGRESS_EVENT = "task-progress";
export const TASK_RESULT_EVENT = "task-result";

export interface GradePdfArgs {
  /** UUID generated by the frontend so it can correlate events with the DB row. */
  taskId: string;
  /** Absolute path to the source PDF (Rule 1 — never bytes). */
  pdfPath: string;
  /** Serialized `OmrTemplate` JSON (read from `templates.json_schema`). */
  templateJson: string;
  /** Serialized `AnswerKey` JSON (validated client-side via `answerKeySchema`). */
  answerKeyJson: string;
}

/**
 * Kick off a batch grade run. Returns immediately; per-page graded results
 * arrive on the `task-result` event and stage updates on `task-progress`.
 */
export function gradePdf(args: GradePdfArgs): Promise<void> {
  return invoke("scan_grade_pdf", {
    taskId: args.taskId,
    pdfPath: args.pdfPath,
    templateJson: args.templateJson,
    answerKeyJson: args.answerKeyJson,
  });
}

export interface RegradeSheetArgs {
  templateJson: string;
  parsedSheetJson: string;
  answerKeyJson: string;
}

/**
 * Re-grade one sheet using a (potentially overridden) `ParsedSheet`. Used by
 * `/review/[job_id]` after the user disambiguates a flagged bubble. Returns
 * the new `GradedSheet`.
 */
export function regradeSheet(args: RegradeSheetArgs): Promise<GradedSheet> {
  return invoke("regrade_sheet", {
    templateJson: args.templateJson,
    parsedSheetJson: args.parsedSheetJson,
    answerKeyJson: args.answerKeyJson,
  });
}

/**
 * Rasterize the first page of a PDF into a PNG via pdfium-render and return
 * the absolute path to the cached image. Used by the P1 template editor to
 * import a PDF as the canvas backdrop.
 */
export function rasterizePdfFirstPage(pdfPath: string): Promise<string> {
  return invoke("rasterize_pdf_first_page", { pdfPath });
}
