import { invoke } from "@tauri-apps/api/core";
import type { GradedSheet } from "$lib/types/generated/GradedSheet";

/**
 * Event names emitted by `commands::scan`. Frontend listeners use these
 * constants instead of bare strings so renames stay in sync.
 */
export const TASK_PROGRESS_EVENT = "task-progress";
export const TASK_RESULT_EVENT = "task-result";

export interface GradePdfArgs {
  /** UUID generated by the frontend so it can correlate events with the DB row. */
  taskId: string;
  /** Absolute path to the source PDF (Rule 1 — never bytes). */
  pdfPath: string;
  /** Serialized `OmrTemplate` JSON (read from `templates.json_schema`). */
  templateJson: string;
  /** Serialized `AnswerKey` JSON (validated client-side via `answerKeySchema`). */
  answerKeyJson: string;
}

/**
 * Kick off a batch grade run. Returns immediately; per-page graded results
 * arrive on the `task-result` event and stage updates on `task-progress`.
 */
export function gradePdf(args: GradePdfArgs): Promise<void> {
  return invoke("scan_grade_pdf", {
    taskId: args.taskId,
    pdfPath: args.pdfPath,
    templateJson: args.templateJson,
    answerKeyJson: args.answerKeyJson,
  });
}

export interface RegradeSheetArgs {
  templateJson: string;
  parsedSheetJson: string;
  answerKeyJson: string;
}

/**
 * Re-grade one sheet using a (potentially overridden) `ParsedSheet`. Used by
 * `/review/[job_id]` after the user disambiguates a flagged bubble. Returns
 * the new `GradedSheet`.
 */
export function regradeSheet(args: RegradeSheetArgs): Promise<GradedSheet> {
  return invoke("regrade_sheet", {
    templateJson: args.templateJson,
    parsedSheetJson: args.parsedSheetJson,
    answerKeyJson: args.answerKeyJson,
  });
}

/**
 * Rasterize the first page of a PDF into a PNG via pdfium-render and return
 * the absolute path to the cached image. Used by the P1 template editor to
 * import a PDF as the canvas backdrop.
 */
export function rasterizePdfFirstPage(pdfPath: string): Promise<string> {
  return invoke("rasterize_pdf_first_page", { pdfPath });
}

export interface ScanAnswerKeyArgs {
  /** UUID generated by the frontend to correlate `task-progress` events. */
  taskId: string;
  /** Absolute path to the scanned single-page PDF (Rule 1 — never bytes). */
  pdfPath: string;
  /** Serialized `OmrTemplate` JSON (read from `templates.json_schema`). */
  templateJson: string;
  /** Target exam id — diagnostic only; persistence stays on the frontend. */
  examId: number;
  /** Target variant label the scan fills, e.g. `"A"`. */
  variant: string;
}

/**
 * Result of `scan_answer_key`. `answers`, `uncertainGroups`, and `groupIds` are
 * index-aligned: `answers[i]` is the read option index for the question group
 * `groupIds[i]` (`-1` means blank), and `uncertainGroups` holds the `i` values whose
 * reading landed in the `[0.35, 0.65]` band and need manual confirmation.
 *
 * Field names are snake_case because the Rust struct serializes its field names
 * verbatim across the IPC boundary (no `rename_all`).
 */
export interface AnswerKeyImportSummary {
  answers: number[];
  uncertain_groups: number[];
  group_ids: string[];
  page_count: number;
  source_path: string;
  preview_path: string;
}

/**
 * Read one hand-filled OMR sheet as the answer key for `(examId, variant)`. Returns the
 * per-group readings for the review screen; stage updates stream on `task-progress`.
 * Rejects multi-page input with `AppError { code: "answer_key_multi_page" }`.
 */
export function scanAnswerKey(
  args: ScanAnswerKeyArgs,
): Promise<AnswerKeyImportSummary> {
  return invoke("scan_answer_key", {
    taskId: args.taskId,
    pdfPath: args.pdfPath,
    templateJson: args.templateJson,
    examId: args.examId,
    variant: args.variant,
  });
}
